### ISSUE TITLE
Possibility to change cave generation in CGTT versions

### ISSUE THREAD

**Issue by SeaGlowingPro** [nasko222/the-minecraft-recreation-project#100]
Me and "Vector Graphics" _found the method for cave generation_ in the CGTT versions. Notch explained the cave generation, however we might not fully understand it. But, the generation is actually replicated in one of Vector Graphics's games.

Video link: https://www.youtube.com/watch?v=qvuROTCOKlg

IRC Logs:
```
[20:01:10] <Notch> i place a number of random blocks, then I iterate MAAANY times, picking random tiles. If the tile is immediately next to another tile, I make the new tile a copy of that first tile
[20:01:13] <Notch> *block
```

How to replicate the generation:
1. Go to https://orteil.dashnet.org/experiments/life
2. Set the rules to: **B5678S45678**
3. Look at the output image

**Comment by nasko222** [comment]
what's wrong with the current cave gen though? its like, amazing

**Comment by Vector-Graphics** [comment]
Note: It isn't exactly this. The site provided applies each iterstion all at once to the entire grid, whiel Notch simply picked blocks at random to modify individually. If the block is more than 50% surrounded by stone, it becomes stone, if it's less than 50%, it becomes grass, and if it is 50%, it stays the same. Mess with the parameters (# of iterations) until it matches the CGTT video i guess.

**Comment by SeaGlowingPro** [comment]
There's nothing wrong with the generation, however, we found the actual method of cave generation used in the real version.

**Comment by Vector-Graphics** [comment]
I said less than 50% becomes grass, I meant air, whoops.

**Comment by Vector-Graphics** [comment]
note: 256x256x64 = 4194304, so 4194304 random blocks iterated is the rough equivalent of one iteration on Prteil's site (that is if CGTT uses the full height limit anyway, which I don't think it does). And just in case you need to know, we're checking a 3x3x3 cube, not a square.

**Comment by Vector-Graphics** [comment]
bruhhhhhh
plx add this lol

**Comment by nasko222** [comment]
didnt we already do this

**Comment by SeaGlowingPro** [comment]
Re-opened after a long while. The cave generation has been re-coded and backported to one of the CGTT versions (specifically pc-131655)

Note: Takes around 20 seconds to generate a map, which is exactly what Notch experienced in the original version.

![Capture](https://github.com/nasko222/the-minecraft-recreation-project/assets/126473525/efcc7cc5-43c5-4009-9dae-e2a0a6e4ec67)

**Comment by SeaGlowingPro** [comment]
Is this final, or are we keeping the original remake? (the one with backported 11a cave generation code)

**Comment by nasko222** [comment]
i need to test it, i will later

**Comment by nasko222** [comment]
uh im not sure, the generation looks much more blocky than the image and the current recreation

![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/52720373/982b5681-7546-4ee4-b18a-f44cb7efe3de)

![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/52720373/92362337-774b-4ee3-911b-bf42b5465355)


on top of that instead of the chunks generating slowly my game lag spikes until theyre all generated

**Comment by nasko222** [comment]
maybe we stick with the old one

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/d0a13b0c-f40a-485a-96bc-948fea102d54)

You could add, there would be more nostalgia for the old minecraft. Please add these caves.

**Comment by nasko222** [comment]
i believe the current 131648 and 131655 are visually more accurate to the video

**Comment by CreepyTDYA** [comment]
I dont know, I do not know much about them. okay

**Comment by CreepyTDYA** [comment]
https://www.youtube.com/watch?v=9aHSjwBQLkk
I reduced the generation of caves and teleportation around the world in height, because I was lagging in those moments.
It looks a bit like a orig CG in 360p.

**Comment by CreepyTDYA** [comment]
if I fix it up a little, maybe I'll send it here, or to someone

**Comment by Vector-Graphics** [comment]
Just... lower the number of iterations from 50 million to something like 25 million and see how it works out

**Comment by CreepyTDYA** [comment]
i broke intellij idea
he's not working
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/918abdd3-6208-4451-9fae-f1ab428fed88)

**Comment by JONESTHEBIRD** [comment]
Wow this looks pretty accurate. It is messy like it's should be

**Comment by JONESTHEBIRD** [comment]
So, the current rd-131655 remake is kinda accurate with the world size. From what's is shown in the screenshot SeaGlowingPro posted a week ago, I can say it looks really accurate to me. More accurate than the current remake

**Comment by CreepyTDYA** [comment]
It's just a matter of thinking about whether this remake will be added or not, because if you look at the remake more precisely at the moment, then these are just expanded caves from c0.0.11a (or c0.0.3a), and if you don't really look into the caves, it will look like the original. The future remake will be much more accurate and nostalgic for CGTT. It is better to choose the second option here.

**Comment by CreepyTDYA** [comment]
Speaking of CGTT. In our remake, there are 6 layers of grass, and in the wiki it says that in CGTT. You can even count how many layers of grass there are in the video, there are 7 of them. Please correct

**Comment by CreepyTDYA** [comment]
![Screenshot_20240319_142453](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/82bb0396-a76c-4697-87d0-bc6c7112854b)
Remake

**Comment by CreepyTDYA** [comment]
![Screenshot_20240319_142715](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/7d3fe4d2-4d4e-4318-961c-7acfef4b5eec)
Original

**Comment by CreepyTDYA** [comment]
I have to create a separate Issue for this
Well, what is already there

**Comment by CreepyTDYA** [comment]
lol I also wanted to do it, but you beat me to it.

**Comment by JONESTHEBIRD** [comment]
Also a Idea would be a test repo or sth like this with multiple testers who than give feedback if the new remake is perfect or if it's not what to improve..

**Comment by nasko222** [comment]
you can always revert the repo back in time


also i have decided and my decision is to keep the new one but improve it slightly because it lag spikes on start and is annoying

and i decided that this repo wont cover any builds before 131655 because they are based on speculations from parties that statements collapse each other and id like to avoid confusion

**Comment by nasko222** [comment]
im going to update pre-classic branch later.

**Comment by nasko222** [comment]
[testing.zip](https://github.com/nasko222/the-minecraft-recreation-project/files/14723258/testing.zip)
for whoever wants to test, heres the 131655 SeaGlowingPro has prepared us.

**Comment by JONESTHEBIRD** [comment]
It's not giving me lag spikes. It just opens a black window and then after 20 seconds it puts me into the world then the chunks start loading. Everything preformance-related looks fine on my end

**Comment by nasko222** [comment]
yep same, very good

**Comment by JONESTHEBIRD** [comment]
let's try to get the seed from the cave game tech test video :tf:

**Comment by CreepyTDYA** [comment]
I moved the cave generation to pc-131648

**Comment by CreepyTDYA** [comment]
just move rubydung and level classes on 1648

**Comment by CreepyTDYA** [comment]
I'm thinking now how to add generation in the build to pc-131655

**Comment by CreepyTDYA** [comment]
on all builds except pc-131951 and pc-131151, you need to drag the level class.

**Comment by CreepyTDYA** [comment]
on this version bug with grass layers
just look
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/efeaae4e-e108-45c6-9e10-32cf0e1fa04b)

**Comment by CreepyTDYA** [comment]
I do not know what to do here.

**Comment by JONESTHEBIRD** [comment]
> on this version bug with grass layers just look ![image](https://private-user-images.githubusercontent.com/159472635/316222984-efeaae4e-e108-45c6-9e10-32cf0e1fa04b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzc2MjQsIm5iZiI6MTcxMTE3NzMyNCwicGF0aCI6Ii8xNTk0NzI2MzUvMzE2MjIyOTg0LWVmZWFhZTRlLWUxMDgtNDVjNi05ZTEwLTMyY2YwZTFmYTA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QwNzAyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjRjN2RmYjc5NzUxMTY3MjllZTQ5YzljZjE5ZTQxOGNhNWQ2NDI4YTRmMzQ5YjRiZTcwODc1NDM1NzM1NjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fR0RiOWMqQagKSOz3zHFplqh_CgtyqgP5hGAg068KNM)

I think it's because it's not made for working in the pc-131648 remake

**Comment by CreepyTDYA** [comment]
It could be anything

**Comment by CreepyTDYA** [comment]
maybe we will stay on the old versions of pc-131951 and 131151

**Comment by JONESTHEBIRD** [comment]
the speculations are no longer supported

**Comment by JONESTHEBIRD** [comment]
The new remake looks good in my opinion

**Comment by CreepyTDYA** [comment]
I agree with you.
All that remains is to find the world on which Notch played.

**Comment by JONESTHEBIRD** [comment]
This was a joke 💀 We cannot find notch's world. The chance to do so is like 1/4,000,000,000

**Comment by CreepyTDYA** [comment]
I know the chances are pretty slim here.

**Comment by JONESTHEBIRD** [comment]
also currently, there's no saving :(
Hope we get a saving mod or sth like this soon

**Comment by CreepyTDYA** [comment]
nasko222 prays for him to add this
we already had a hard time forcing him to change the pre-classic branch

**Comment by CreepyTDYA** [comment]
more precisely, he thought of it himself

**Comment by JONESTHEBIRD** [comment]
I wonder were the minecraft wiki gets the info from, that saving was added in pc-132011. The only reference linked is the rd-132211.json

**Comment by CreepyTDYA** [comment]
maybe they just didn't know about the builds before rd-132211, and then they would have created a separate page with the development of rd-132211

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/df749ae4-f2e0-4d06-a99b-bf47945327c5)

nothing is written about saving, maybe saving was actually added only in 2211?

**Comment by CreepyTDYA** [comment]
I have read everything that is closer to this time, there is not a single word about saving

**Comment by CreepyTDYA** [comment]
most likely he forgot to write about it

**Comment by JONESTHEBIRD** [comment]
Yeah. It could've been around pc-132011 but it also could've been added on May 12th as well
I think making a saving mode for it is pretty simple. Just add the saving method (and also the loading method) from pc-132011 to the level.class in the pc-131655 remake and call it in the main class like pc-132211 does.

**Comment by CreepyTDYA** [comment]
I'm going to test it now

**Comment by JONESTHEBIRD** [comment]
I know for a fact that the code of notch remake had saving

**Comment by CreepyTDYA** [comment]
lol Maybe they know the story better than we do.

**Comment by JONESTHEBIRD** [comment]
But please don't use the code of notch remake. the generation just sucks

**Comment by CreepyTDYA** [comment]
there you need to copy one line that allows you to save the world in the level.dat file

**Comment by CreepyTDYA** [comment]
I forgot that I won't be able to work with versions right now, because my program gives an error when starting the game.

**Comment by JONESTHEBIRD** [comment]
Only SeaGlowingPre can make a saving mod rn iirc

**Comment by CreepyTDYA** [comment]
I'm going to try to do something with pc-131151 now, because I don't like
it later I'll do pc-131951

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/e9086d2d-fb24-4998-b9db-d382db72b257)
lol

**Comment by CreepyTDYA** [comment]
I'm tired of it somehow, I'll continue a little later, it really pisses me off that all my attempts to do this stuff don't work

**Comment by JONESTHEBIRD** [comment]
Because you don't have the source code

**Comment by nasko222** [comment]
> on this version bug with grass layers
> just look
> ![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/efeaae4e-e108-45c6-9e10-32cf0e1fa04b)
> 

is this in the new testing version that i sent above?

**Comment by CreepyTDYA** [comment]
I want to transfer the generation to pc-131151

**Comment by CreepyTDYA** [comment]
but there is another problem
this one

**Comment by nasko222** [comment]
theres no such thing as 131151 here, i am asking if the version i sent above in "testing.zip" caused the grass bug from your image

**Comment by CreepyTDYA** [comment]
No, because I was showing a picture of a different version.

**Comment by nasko222** [comment]
ok but please clarify that because you posted this after my testing zip so it could cause confusion

**Comment by CreepyTDYA** [comment]
I signed on top that I am working on builds up to pc-131655

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/e02ba793-5657-4b65-953e-98f47925cbc2)
i create this but sky is black

**Comment by nasko222** [comment]
anyway in conclusion the new build is done, preclassic will be updated later thanks SGP and Vector

**Comment by JONESTHEBIRD** [comment]
> theres no such thing as 131151 here, i am asking if the version i sent above in "testing.zip" caused the grass bug from your image

He is messing around with the code

**Comment by JONESTHEBIRD** [comment]
trying to do saving and porting the generation to speculation
but yk what happens when you try editing compiled code XD
