### ISSUE TITLE
Building in pc-131208/rd-131408

### ISSUE THREAD

**Issue by Vector-Graphics** [nasko222/the-minecraft-recreation-project#101]
[14:08:46] /Notch> Riven_: 100 ms lag spikes make the game unplayable right now, and they happen every time a block changes.. soo.. :-\

This IRC log implies that there was building in this version, but it was very laggy and it was likely removed as part of trying to fix the performance.

**Comment by nasko222** [comment]
What? it's unlikely building exists because we know for sure it doesnt exist in CGTT....... It could mean loading a chunk or the N key was working later on and you could change the blocks. I mean in pc-131137 pressing the N key lags the game significantly high

**Comment by Vector-Graphics** [comment]
I theorized that it was removed between 131208 and 131655 as part of Notch's attempt to fix performance. And then was readded in 131951

**Comment by nasko222** [comment]
Remove a feature to fix a bug? Sounds like a notch thing to do

**Comment by nasko222** [comment]
Won't fix (For now)

**Comment by Vector-Graphics** [comment]
![image](https://user-images.githubusercontent.com/62966659/235343490-6fd08a0c-dcb5-43c9-8a6b-dc8712c529e9.png)
This irc log talks about block updates affecting a single chunk at 11:56 (I think).

**Comment by TristanCorso911** [comment]
Placing and Breaking Blocks was added in rd-132151.

**Comment by TristanCorso911** [comment]
Nasko222 wants to make the mods

**Comment by nasko222** [comment]
Nasko222 doesn't want to make the mods. Nasko222 is lazy as fuck!

**Comment by TristanCorso911** [comment]
Building was added in pc-131951/rd-132151
