### ISSUE TITLE
c0.0.0a and c0.0.1a (numbered version)

### ISSUE THREAD

**Issue by Nicky20228** [nasko222/the-minecraft-recreation-project#102]
I was just watching YouTube for some reason when I saw both Minecraft farm tour and The Massive City on a YouTube channel named Every Minecraft Version that shows both c0.0.0a and c0.0.1a (numbered version) that are basically a version gap between mc-161648 and c0.0.2a so could you remake both of these two versions please?

**Comment by nasko222** [comment]
the every minecraft version channel is an ARG lmao
