### ISSUE TITLE
in-20091231-2 dev build and in-20091231-1 shouldn't have item dropping

### ISSUE THREAD

**Issue by minecraft12y** [nasko222/the-minecraft-recreation-project#103]
![image](https://user-images.githubusercontent.com/115079405/235370261-787deb1f-f717-4794-9e7b-28f4b5fd0396.png)
notch made this blogpost announcing his progress with items and what he still had to do, also mentioning he's yet to add "items laying around on the ground", suggesting block dropping was added in 20091231-2, and which as such should be removed from the 20091231-1 remake unless proven otherwise.

**Comment by minecraft12y** [comment]
Actually, seeing how he worded it, it's either dropping entirely was added in 1231-2 OR only items in this dev build couldn't be dropped yet. I suppose the latter makes more sense.

**Comment by nasko222** [comment]
"Make it possible to drop items and block" Yes dropping definitely doesnt exist in 1231-1. And having a dev build about that would make sense as well. I will recreate them when I have time

**Comment by nasko222** [comment]
forgot to close, its fixed now and we got new -1 and in between 1 and 2, dev
