### ISSUE TITLE
c0.0.15a-6

### ISSUE THREAD

**Issue by TristanCorso911** [nasko222/the-minecraft-recreation-project#104]
Minecraft Classic 0.0.15a (Multiplayer Test 6) was released on June 4, 2009 at 16:51 UTC, Changed the level sending code to pause whenever a new player logs in.

**Comment by nasko222** [comment]
MPTest 6 does not work, Check the Wiki.

**Comment by TristanCorso911** [comment]
Please how to code c0.0.15a-6

**Comment by nasko222** [comment]
idk xd

**Comment by TristanCorso911** [comment]
This version didn't launch

**Comment by nasko222** [comment]
while (true) sleep(1);

MY BROTHER IN CHRIST YOU ESTABLISHED THE MECHANIC!1!11!1!1!1!1!!
