### ISSUE TITLE
c0.0.11a-dev1 has 64x64x64 blocks

### ISSUE THREAD

**Issue by TristanCorso911** [nasko222/the-minecraft-recreation-project#116]
The map is 64x64x64 blocks.

**Comment by nasko222** [comment]
this is also the update that added the backrooms, sadly it never saw the light of day

**Comment by TristanCorso911** [comment]
How do you code 11a-dev1?

**Comment by TristanCorso911** [comment]
Here's my video: https://youtu.be/I6Kz6DgUnyg
