### ISSUE TITLE
c0.0.11a has 3 developer builds

### ISSUE THREAD

**Issue by TristanCorso911** [nasko222/the-minecraft-recreation-project#117]
I coded this c0.0.11a-dev has 64x64x64 blocks and c0.0.11a-dev2 has 128x128x64 blocks or c0.0.11a-dev3 has 256x256x64 blocks on Eclipse. That's it! No more

**Comment by nasko222** [comment]
No more??????? what about dev12 herobrine test, dev44 minecon 2008 rewind test, dev58 notch test, test test, dev92233nottypingallat dank memes r real test???????

**Comment by TristanCorso911** [comment]
I coded c0.0.11a-dev and dev2 or dev3
