### ISSUE TITLE
BlueStaggo: I discovered a potential developer version myself, which I dub 12w03a-dev and 12w03a-dev2. Both of these versions were shown by Jeb and feature early Jungle trees with oak leaves and spruce trunks, although these could just be early jungle log and leaves textures. The large trees in the first dev version have a more bulbous shape and lacked branches. These are found in [this tweet](https://twitter.com/jeb_/status/159616418575421440) and [that tweet](https://twitter.com/jeb_/status/159940561418199041) respectively.

### ISSUE THREAD

**Issue by nasko222** [nasko222/the-minecraft-recreation-project#129]
I discovered a potential developer version myself, which I dub 12w03a-dev and 12w03a-dev2. Both of these versions were shown by Jeb and feature early Jungle trees with oak leaves and spruce trunks, although these could just be early jungle log and leaves textures. The large trees in the first dev version have a more bulbous shape and lacked branches. These are found in [this tweet](https://twitter.com/jeb_/status/159616418575421440) and [that tweet](https://twitter.com/jeb_/status/159940561418199041) respectively.

![12w03a-dev](https://i.imgur.com/XaVJu.png)
![12w03a-dev2](https://i.imgur.com/Li3Ak.png)

 One funny thing I discovered is that jungles in Minecraft were shown off around the same time jungles in Cube World were shown off:
 
![Wolfram von Funck @wol_lay: "New Cube World Screenshots: Jungle goo.gl/fb/VwuBw"; Jens Bergensten @jeb_: "@wol_lay
 Haha, and I was just doing this: http://i.imgur.com/XaVJu.png"](https://github.com/nasko222/the-minecraft-recreation-project/assets/71090710/64b2b4ae-0315-4065-be75-6b6c1e29bbda)

_Originally posted by @BlueStaggo in https://github.com/nasko222/the-minecraft-recreation-project/discussions/92#discussioncomment-5887962_

**Comment by nasko222** [comment]
Referencing @BlueStaggo's post from the Discussion

TODO: Make these two devs :D

**Comment by nasko222** [comment]
james cope + banned + l bozo

**Comment by nasko222** [comment]
https://cdn.discordapp.com/attachments/1066290331483656235/1108065279717675028/image.png

**Comment by nasko222** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/52720373/14bc3bbf-8e96-46f3-915e-1fa5521af3ff)
Progress on this, i will upload them tomorrow

**Comment by TheNamesJamesYT** [comment]
didnt ask snigger

**Comment by TheNamesJamesYT** [comment]
l bozo + cope

**Comment by nasko222** [comment]
stop being toxic lmao

**Comment by TheNamesJamesYT** [comment]
lmao

**Comment by nasko222** [comment]
Done
