### ISSUE TITLE
pc-131951 should be pc-131751

### ISSUE THREAD

**Issue by Vector-Graphics** [nasko222/the-minecraft-recreation-project#130]
If you look at the IRC logs from which we got the May 13th Pre-Classic timestamps, the references to pc-131655 are actually at 18:55, meaning that 131951 (the timestamp from the IRC) is actually the RD timezone version and the UTC version is 131751

**Comment by nasko222** [comment]
its rd-132151 so its logical to be pc-131951, i am going by the omni version numbering

**Comment by Vector-Graphics** [comment]
the thing is
it's rd-131951, I looked at the logs.
So it should be pc-131751
