### ISSUE TITLE
Minecraft Indev 20100224 and Minecraft Infdev 20100304

### ISSUE THREAD

**Issue by Nicky20228** [nasko222/the-minecraft-recreation-project#133]
Hi I just discovered indev February 24 2010 and infdev March 4 2010 these are actually developer builds from February and March 2010 respectively and I was wondering if you could make both of them please nasko I really wanted one indev build and one infdev build so could you please do it?

**Comment by nasko222** [comment]
Send proof/evidence/changelog ?

Also the march 4 infdev could be the march 8 infdev ive made

**Comment by Nicky20228** [comment]
I just found it on a Minecraft wiki page called Developer version at the middle of list of known developer builds called Indev.

**Comment by nasko222** [comment]
Yea well i've seen this many times, Everyone can write whatever they want on the internet. That means nothing to me

**Comment by nasko222** [comment]
If you find Images or notch blog send me links then and reopen this

**Comment by Nicky20228** [comment]
Sorry nasko I tried to find notch’s blog about indev 20100224 and infdev 20100304 but they didn’t have information about it.

**Comment by nasko222** [comment]
ok

**Comment by Nicky20228** [comment]
But there are actually other few indev and infdev builds that are never released to the public so maybe you should make those builds right?

**Comment by nasko222** [comment]
Which builds?
