### ISSUE TITLE
View Bobbing in 0.24 dev10 and new dev

### ISSUE THREAD

**Issue by minecraft12y** [nasko222/the-minecraft-recreation-project#139]
notch said this in irc on august 21: 
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/115079405/1ce03620-c928-4bf1-b90c-5ed7fedd74f4)
However, a while before this, he sent this message, most likely being about dev9: 
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/115079405/918dd13e-a5f6-4610-9853-492e73f4dcda)
As such there should be a new dev between dev9 and 10 that adds view bobbing, and it should be added to dev10, with the behavior of dev11, also being toggleable from the options.

**Comment by nasko222** [comment]
maybe some other day
