### ISSUE TITLE
a1.2.0 new dev

### ISSUE THREAD

**Issue by minecraft12y** [nasko222/the-minecraft-recreation-project#144]
There's this article on PCGamer that predates the blogpost notch made about biomes and that features portals: https://www.pcgamer.com/minecraft-halloween-update-preview-meet-the-ghasts/
As such, there should be a new dev between dev2 and 3 that adds portals, and portals should be in dev3 and 4. 
Notch probably also made it so you spawn with obsidian and a flint and steel alongside the torches so PCGamer could make portals.

**Comment by CrazyCSIW6** [comment]
spawning with obsidian and flint+steel would be plausible but the F4 bind to spawn portals in a1.2.2 exists, implying that could've existed in earlier dev builds as well. unless there's evidence im missing which proves it didn't?

**Comment by minecraft12y** [comment]
Yeah, the F4 key (or any other key) could've been used to spawn the portals before the preview, however there's no evidence for either method currently.

**Comment by TheNamesJamesYT** [comment]
bro is nerdin :skull:

**Comment by nasko222** [comment]
nerdin fr, i forgot to close this
