### ISSUE TITLE
Fence gate inventory icon in b1.8 devs should be a flat wood texture.

### ISSUE THREAD

**Issue by minecraft12y** [nasko222/the-minecraft-recreation-project#148]
In the PAX build, the fence gate in the inventory has a flat wood texture, as seen here: https://www.youtube.com/watch?v=v_jJJTROkJ0&t=91s.
As such, the inventory icon for the fence gate, most likely for all builds that include them, should be a flat wood texture.

**Comment by minecraft12y** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/115079405/ce728e90-9713-47e3-b6ae-30b68a6023c9)
It also had no name as seen in this frame

**Comment by nasko222** [comment]
Merge it with the b1.8 topic
