### ISSUE TITLE
New c0.28 dev build that i found recently

### ISSUE THREAD

**Issue by Nicky2024** [nasko222/the-minecraft-recreation-project#156]
Nasko222! i got exciting news for you today. There is a world of notch post from October 26, 2009 that basically has creative mode reimplemented for the first time since c0.0.23a_01. So I am wondering if you can make a new c0.28 dev build that I can check it out.

**Comment by minecraft12y** [comment]
Okay so seems like there's barely anything different in said dev except for middle clicking not working in creative mode and local saving and loading, though we know nothing about how that would have worked and if it's any different from 0.30.

**Comment by Nicky2024** [comment]
Well basically it was posted before the release of c0.28 so it does count as a dev build nonetheless.

**Comment by nasko222** [comment]
How do I make a build that has no changes at all from the next one? 0.28 is made already and yes it has the bugs you mentioned

**Comment by nasko222** [comment]
omg he is the prophet
