### ISSUE TITLE
pickblock sigh in st 24 devs gives you lava

### ISSUE THREAD

**Issue by G23M08** [nasko222/the-minecraft-recreation-project#159]
if you pick block in any st 24 dev after sighs were added you get lava

**Comment by JONESTHEBIRD** [comment]
I know, but it only happens with mobs

**Comment by G23M08** [comment]
what

**Comment by JONESTHEBIRD** [comment]
if you middle-click on mobs, it'll give you lava. If you middle click on other blocks, it will give you the drop

**Comment by G23M08** [comment]
I know that is that a bug or feature if its a feature sorry

**Comment by nasko222** [comment]
It's a feature

**Comment by G23M08** [comment]
sorry
