### ISSUE TITLE
PAX Preview build seems to still have full block chests,

### ISSUE THREAD

**Issue by ogm846** [nasko222/the-minecraft-recreation-project#162]
The PAX Preview build of Beta 1.8 seems to still have full block chests, you can see in this image that it's the same size as the other blocks here.
![chests](https://github.com/nasko222/the-minecraft-recreation-project/assets/74267163/68ac394a-42c4-4a9a-84d4-843f563d99e0)

**Comment by nasko222** [comment]
that issue is considered with the new hybrid recreations for b1.8 that are work in progress! Thanks

**Comment by ogm846** [comment]
You're welcome!
