### ISSUE TITLE
Almost every indev 3.1 builds crashes

### ISSUE THREAD

**Issue by G23M08** [nasko222/the-minecraft-recreation-project#163]
Only the last 2 builds work for me on betacraft but they work in mineonline 
The builds that don't work just show a black screen

**Comment by nasko222** [comment]
send crash log

**Comment by G23M08** [comment]
As said in the post it just shows a black screen

**Comment by nasko222** [comment]
that i heard, and you can still send the output log

**Comment by G23M08** [comment]
(16:24:17) Java version: Oracle Corporation, Java(TM) SE Runtime Environment, 1.8.0_361-b09
(16:24:17) System: windows 10, 10.0, amd64
(16:24:19) Detected launch method: classic15a
(16:24:19) Loaded in: 1657364200 ns
(16:24:28) 
(16:24:28) Classpath:
(16:24:28) C:\Users\Usuario\AppData\Roaming\.betacraft\versions/in-20091207.jar
(16:24:28) C:\Users\Usuario\AppData\Roaming\.betacraft\bin/jinput.jar
(16:24:28) C:\Users\Usuario\AppData\Roaming\.betacraft\bin/lwjgl.jar
(16:24:28) C:\Users\Usuario\AppData\Roaming\.betacraft\bin/lwjgl_util.jar
(16:24:28) 
(16:24:28) 
(16:24:28) Loading addons:
(16:24:28) 
(16:24:28) java.lang.NoSuchMethodException: com.mojang.minecraft.Minecraft.<init>(java.awt.Canvas, int, int, boolean)
(16:24:28) 	at java.lang.Class.getConstructor0(Unknown Source)
(16:24:28) 	at java.lang.Class.getConstructor(Unknown Source)
(16:24:28) 	at org.betacraft.Classic15aWrapper.init(Classic15aWrapper.java:125)
(16:24:28) 	at org.betacraft.Classic15aWrapper.play(Classic15aWrapper.java:99)
(16:24:28) 	at org.betacraft.Wrapper.<init>(Wrapper.java:183)
(16:24:28) 	at org.betacraft.Classic15aWrapper.<init>(Classic15aWrapper.java:31)
(16:24:28) 	at org.betacraft.launcher.Launcher.main(Launcher.java:207)

**Comment by nasko222** [comment]
load as 0.30 base, (copy 0.30 json and rename it to the same as the jar but ends on .json)
