### ISSUE TITLE
Pre-Classic versions are incorrectly labelled, and some are missing. 

### ISSUE THREAD

**Issue by Vector-Graphics** [nasko222/the-minecraft-recreation-project#166]
INCORRECTLY LABELLED VERSION:
"pc-152244" has no source other than Method... basically guessing (as no IRC log nor tumblr post points to 22:44). The correct version number is 152225, from the Tumblr post about the version (however the exact date of the original files was probably before midnight, due to being interpreted as the 15th by Mojang and the rest of the dates being accurate).

Missing versions:
"pc-131641" is <10 FPS on :thelaptop:, as opposed to pc-131648's 72 FPS.
"pc-131134" (or alternatively, "pc-12" or "pc-20090512" if you prefer) had severe performance issues: a single chunk update took 100 ms on :thelaptop:. Early optimization discussion led to solutions with severe RAM issues, but these were most likely not implemented and are thus not separate versions. 8x8x8 chunks were implemented prior to the mentioned time to try to work out the performance issue. There is no reason for the sky to have been black in this version (unlike the current speculative recreations).

**Comment by CreepyTDYA** [comment]
if you look at the lost pre-classic version of pc-152236, then it does not converge with pc-20090515, or it also needs to be renamed

**Comment by CreepyTDYA** [comment]
pc-152236 would be renamed to pc-152217 (good timestap)

**Comment by nasko222** [comment]
You see guys all of your theories clash, one say 152244 other say 152236 and third now say 152217, And that's not the only case of this happening. I need a standard for this project and I am not sure which one to pick, whichever I pick the rest will be mad it's not that way and call it inaccurate (Not that I care that much what people say on surface level) but come on, if a build like this is based on info so vague at this point the best decision would be not to include it here.

**Comment by Vector-Graphics** [comment]
pc-152236 does not exist.
pc-152217 seems to be an arbitrary name given by Creepy that is not given on actual info. 
pc-152225 is the date of the version's tumblr post, and is correct.

**Comment by nasko222** [comment]
further proves my point

**Comment by Vector-Graphics** [comment]
ok let's just call it pc-20090515 since we can't agree on the precise timestamp.

**Comment by nasko222** [comment]
works for me

**Comment by nasko222** [comment]
I need seperate classic issue, ill make one later

long story short

1a is a seperate version apparently
the mc-1616xx or c-20090516 versions (naming still in question) need some work, they are basically last preclassic but with applet support (and the fps thing idk when its added maybe after 1a or with 1a)
and 2a-dev isnt real
2a and 3a not sure if they will need rework ill have to check
8a idk if its real or not apparently it has broken block preview
9a onwards should be fine

**Comment by CreepyTDYA** [comment]
Why don't you make a numbered c0.0.1a, in the Russian wiki it says that the version number is added in the upper corner.

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/c94817c9-29b0-449f-b5e5-643c22619ac5)

**Comment by CreepyTDYA** [comment]
![image](https://github.com/nasko222/the-minecraft-recreation-project/assets/159472635/2dcc2e87-92a1-4fed-860c-1c4bc010588f)

**Comment by nasko222** [comment]
This project goes by Omniarchive's chronology.

**Comment by nasko222** [comment]
Moving the issue
