### ISSUE TITLE
Indev 20100106 and 20100107 are missing weird mipmapping

### ISSUE THREAD

**Issue by VesuviusVenox** [nasko222/the-minecraft-recreation-project#172]
You may have noticed the darker leaves in Notch's videos from that time. That is not the result of video compression, it's actually some mipmapping he did. He removed it the very next version because of transparency layering issues, but the code for them is still in every version after, just incomplete. You can ask Sith for more details on how to recreate this, as he has done it before for in-223.

**Comment by nasko222** [comment]
fixing brb
