### ISSUE TITLE
A few versions dont work at all

### ISSUE THREAD

**Issue by sigma2424243** [nasko222/the-minecraft-recreation-project#174]
Most indev versions  and pre classic versions  just show a black screen everytime i try using it im on betacraft btw

**Comment by nasko222** [comment]
Not a bug

Use appropriate json (Info) files, Earlier indevs use 0.30 base and preclassics use any preclassic base

**Comment by sigma2424243** [comment]
Ohhh thanks sorry for the dumb questions btw

**Comment by sigma2424243** [comment]
> Not a bug
> 
> Use appropriate json (Info) files, Earlier indevs use 0.30 base and preclassics use any preclassic base

Wait so if i doenlpaded multiple indev dev versions i just duplicate the jsons for both versions
