### ISSUE TITLE
All the versions stopped workiny

### ISSUE THREAD

**Issue by sigma2424243** [nasko222/the-minecraft-recreation-project#177]
a bunch of versions crash every single time i try to use them is there a fix to this i downloaded everything right i did everything and they still crash

**Comment by PhobTDYA** [comment]
Which app do you use to launch the version?

**Comment by githubplayer123-jpg** [comment]
help i use betacraft launcher and when i launch version is a black screen

**Comment by CrazyCSIW6** [comment]
can we like, not have this issue open?
