### ISSUE TITLE
12w03a-dev Trees

### ISSUE THREAD

**Issue by CrumbledHam** [nasko222/the-minecraft-recreation-project#178]
In the Jeb screenshot, the big tree leaves appear to generate in this shape. The base of the leaves being 1 thick and the next layers being 2 thick.

![image](https://github.com/user-attachments/assets/c532c25e-0a49-4483-87c3-0572d0050929)

Whereas in the recreation its the inverse.

![image](https://github.com/user-attachments/assets/6ad8d59e-329c-49ac-a83d-698924aa6e79)

**Comment by nasko222** [comment]
![image](https://github.com/user-attachments/assets/db243882-c19a-4772-8abc-af841f9e4a49)
Good?

**Comment by CrumbledHam** [comment]
Judging by the fuzzy jeb image, the top layer isnt 1 block thick and theres no vines on the big trees.

**Comment by nasko222** [comment]
i can remove the vines, what about the top layer? the code currently goes through 8 iterations for building the leaves base

**Comment by nasko222** [comment]
Oh i guess making them 9 iterations fixes it

**Comment by nasko222** [comment]
modding a snapshot requires to do it without mappings but bare with me

`private void a(vx paramvx, int paramInt1, int paramInt2, int paramInt3, int paramInt4, Random paramRandom) {
    byte b1 = 0;
    byte b2 = 8; // amount of iterations
	int nextIterator = 1;
	int b3 = 0; // shrinker
    paramInt3--;
    for (int i = paramInt3 - b1; i <= paramInt3; i++) {
      int j = i - paramInt3;
      int k = paramInt4 + 1 - j;
      for (byte b = 0; b < b2; b++) {
        
        for (int m = paramInt1 - k + b3; m <= paramInt1 + k + 1 - b3; m++) {
          for (int n = paramInt2 - k + b3; n <= paramInt2 + k + 1 - b3; n++){
            a(paramvx, m, i + b, n, oj.M.bO, this.c); 
		  }
        } 
		nextIterator++;
		if (nextIterator >= 2){
			nextIterator = 0;
			b3++;
		}
      } 
    } 
  }`

**Comment by CrumbledHam** [comment]
The small trees probably generate with vines. The random vines is probably for the ground shrubs and isnt added yet.

**Comment by nasko222** [comment]
![image](https://github.com/user-attachments/assets/7afa0819-4186-4958-b6e0-0257caf38803)
![image](https://github.com/user-attachments/assets/28e34504-c851-4b93-8e14-5446b5bb8db0)

**Comment by nasko222** [comment]
Good ?

**Comment by CrumbledHam** [comment]
Nice. Hard to tell but do all the big trees in the jeb screenshot have 4 layers only?

**Comment by nasko222** [comment]
I believe, I am hashing and uploading the new one

**Comment by CrumbledHam** [comment]
I mean I can only see trees in jebs screenshot with 4 layers of leaves. The recreation screenshots have up to 5.

**Comment by nasko222** [comment]
![image](https://github.com/user-attachments/assets/03943808-66ad-429e-9377-04f2037e91e6)

**Comment by nasko222** [comment]
![image](https://github.com/user-attachments/assets/6db628cc-d389-4cb5-b781-827a1e5f0c2e)

**Comment by CrumbledHam** [comment]
Ah possibly. I was thinking its another 2 layer thick one
