### ISSUE TITLE
White / Black screen on Minecraft 0.0.10c

### ISSUE THREAD

**Issue by cooperative3035** [nasko222/the-minecraft-recreation-project#183]
I'm getting a white or black screen when trying to open Minecraft version 0.0.10c, i tried MultiMC and Betacraft, both failed. I also tried to use Java 7 instead of 8, that didn't help. The logs seem to be clear:

```
Minecraft process ID: 13856


Using onesix launcher.

Could not find Minecraft path field.
Launching with applet wrapper...

```

I also made the c0.0.10a.info file and it didnt change anything.

**Comment by cooperative3035** [comment]
Nevermind.

**Comment by CreepyTDYA** [comment]
ok
