### ISSUE TITLE
The number of remakes we have isn't even half of the number of missing versions/dev builds.

### ISSUE THREAD

**Issue by SeaGlowingPro** [nasko222/the-minecraft-recreation-project#88]
It was recently found out that the versions found by Omniarchive have been faked. In this case, we will try to recreate the faked versions, starting from pc-132011.

**Comment by Vector-Graphics** [comment]
isn't 132011 provided in the launcher? i think the first omni version is 12a

**Comment by SeaGlowingPro** [comment]
This bug report is a joke.
It's for April Fools.
