### ISSUE TITLE
Early Dynamic lighting testing and Wall-hack protection

### ISSUE THREAD

**Issue by Nicky20228** [nasko222/the-minecraft-recreation-project#99]
Hey nasko I was just looking at a World of Notch post from December 19 2009 about testing dynamic lighting and Implementing a form of wall-hack protection so could you remake these other 2 December 19 builds of indev please?

**Comment by nasko222** [comment]
the wallhack protection is likely part of the server software, as of the dymamic lighting, the 1219 build has actually no changes and the 1220 build applies the new lighting, we dont need more repetitive builds
